---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - GgBlogPostExtension
SilverStripe\Blog\Model\BlogTag:
  extensions:
    - GgBlogTagExtension
Topic:
  extensions:
    - TopicExtension
TopicHolder:
  extensions:
    - TopicHolderExtension
LocationPage:
  extensions:
    - Symbiote\Addressable\Addressable
    - Symbiote\Addressable\Geocodable
