BlogTag:
  extensions:
    - GgBlogTagExtension
Topic:
  extensions:
    - TopicExtension
TopicHolder:
  extensions:
    - TopicHolderExtension
LocationPage:
  extensions:
    - Addressable
    - Geocodable